### ISSUE TITLE
FileNotFoundException when loading

### ISSUE THREAD

**Issue by TrademarkTM** [krmn08/MCScript#1]
I'm having a `FileNotFoundException`when reloading the plugin, probably because of special characters in my server path (spaces, accents):
```
java.io.FileNotFoundException: D:\Arquivos\Área%20de%20Trabalho\Jogos\Servidores\1.14.4\cache\patched_1.14.4.jar (O sistema não pode encontrar o caminho especificado)
[23:46:37 WARN]:        at java.util.zip.ZipFile.open(Native Method)
[23:46:37 WARN]:        at java.util.zip.ZipFile.<init>(ZipFile.java:225)
[23:46:37 WARN]:        at java.util.zip.ZipFile.<init>(ZipFile.java:155)
[23:46:37 WARN]:        at java.util.jar.JarFile.<init>(JarFile.java:166)
[23:46:37 WARN]:        at java.util.jar.JarFile.<init>(JarFile.java:103)
[23:46:37 WARN]:        at com.krmnserv321.mcscript.MCScript.getBukkitClasses(MCScript.java:437)
[23:46:37 WARN]:        at com.krmnserv321.mcscript.MCScript.reload(MCScript.java:288)
[23:46:37 WARN]:        at com.krmnserv321.mcscript.MCScript.onCommand(MCScript.java:98)
[23:46:37 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
[23:46:37 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[23:46:37 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739)
[23:46:37 WARN]:        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:701)
[23:46:37 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:456)
[23:46:37 WARN]:        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418)
[23:46:37 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098)
[23:46:37 WARN]:        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925)
[23:46:37 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

Are there any workarounds for the problem for now?
Nice project by the way. I really liked the language structure.

Unrelated question: how do you use events that aren't Bukkit events?

**Comment by krmn08** [comment]
Thank you for the report.
A URL bug was fixed. Try it with the latest version.
Modified so that events other than Bukkit events can be written in the same way.
